server:
  port: 8090
spring:
  data:
    mongodb:
      username: saoussen
      password: saoussen
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin